### ISSUE TITLE
Xtreme 2 GG Downgrade?

### ISSUE THREAD

**Issue by M4lw4reT3sts** [pembem22/connect-plus#49]
Hello pembem22 I have been looking all over the internet to downgrade my JBL Xtreme 2 and I have no clue how these files of yours work and you are probably the only person that can help me. I'm clearly not a fan of the latest update and I'm trying everything for a downgrade so can you (or anyone reading this) help me

**Comment by M4lw4reT3sts** [comment]
I see I've already closed this issue btw I got one question how do I flash the firmware of a partyboost speaker using the connectplus app because the Flip 5 doesn't support your app

**Comment by flavius2703** [comment]
can please someone offer suport for downgrade?

**Comment by jackhhhhhsa** [comment]
How do I install the downgrade? I have the version 2.3 for the xtreme 2 but can’t figure out how to install it can someone help?

**Comment by XboxOneSogie720** [comment]
Go to the DFU flash section of the app. I believe it's the third tab at the bottom, and follow the instructions.

**Comment by jackhhhhhsa** [comment]
Hey is there a specific model that the speaker has to be for the car chipset because I have a version 2.4 pl and a version 2.7 gg and they both have qcc chipsets

**Comment by moontan109** [comment]
Hi. I'm not able to connect the app to my Flip 6 TT. It's stuck at 'connecting to Flip 6....'. Is there a reason something is blocking the app from connecting?

**Comment by Rocknr1000TTV** [comment]
can someone send me the file for JBL firmware version 2.3.0 - 2.5.0 as I don't want to use an unofficial build
