### ISSUE TITLE
Downgrade jbl xtreme 2

### ISSUE THREAD

**Issue by Pyerix101** [pembem22/connect-plus#54]
Hi, a just saw this project because i was looking for a way to downgrade ma xtreme 2, i don't know what model is my jbl but i think it's GG, what firmaware can i download and how can i sucessfully downgrade the speaker without bricking it? thanks
photo of the back:
![WIN_20220219_14_43_13_Pro](https://user-images.githubusercontent.com/76700360/154803344-28cacd55-e576-4834-8f86-44a1d5da16d4.jpg)
s

**Comment by pembem22** [comment]
Hi, you should use the app to check what platform (CSR, QCC or Vimicro) your speaker uses and see if there are firmware files for your model available. Flashing custom firmware is not officially supported and I cannot guarantee any successful result.
