### ISSUE TITLE
Implement this app features in Gadgetbridge

### ISSUE THREAD

**Issue by jensen-n** [pembem22/connect-plus#67]
Hi!
You may not know [Gadgetbridge](https://gadgetbridge.org) yet. It's an open-source app that aims to add support for every gadget in one app! No need for dozens suspicious apps for every different devices. We already support dozens devices.

We are adding support for JBL Charge [2](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/3101)/[3](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/3102)/[5](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/3103) and [JBL Flip 6](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/3110) (and others if someone asks). Your work on ConnectPlus is very helpful, thanks for that. Are you interested in participating in this and implementing your app's features in Gadgetbridge?

**Comment by pembem22** [comment]
Hi, thanks for letting me know about such a project! I agree, it would be great to add support for JBL speakers into a universal app. 

But I'm not sure if I can help you with that right now. I don't spend much time developing my app, let alone porting all the functionality to a different one. However, I'm open to this idea in the future.
