### ISSUE TITLE
Can't find what platform my jbl speaker is on 

### ISSUE THREAD

**Issue by pizzi2401** [pembem22/connect-plus#68]
Hy guys I've been trying to find on what platform my jbl etreme 2 is but it doesn't appear on the app 
Connect-plus . Is there any other way to do it ?
Here's a screenshot of the app : 
![IMG_20230604_105533](https://github.com/pembem22/connect-plus/assets/135505210/626657c1-832b-4ba5-8498-088f6cdbabb5)

**Comment by pizzi2401** [comment]
Sorry if my English is a bit messy it is not my first language

**Comment by pembem22** [comment]
Use the latest 1.2.0 version of the app, you can find it in the releases list.

**Comment by pizzi2401** [comment]
Alright! Thank you very much !
