### ISSUE TITLE
Would You Like Help With an iOS Port?

### ISSUE THREAD

**Issue by XboxOneSogie720** [pembem22/connect-plus#71]
I know a little about SwiftUI. By the looks of your UI, I think I could easily do some learning about SwiftUI in order to properly implement the same look on iOS. I can create an app that supports all devices on iOS 15.0 and up. Let me know if I should make a fork or just my own repository. 

Btw, I think an alternative name, and more appropriate name in my opinion, could be "Connect++" or "Connect Plus Plus" since it's just "Connect Plus" with more features :P

I'm going to get started soon, but I won't publish it without your permission here. Thanks!

If you want to get something sorted out, please DM me on Discord: [xboxonesogie720]. Btw something weird happened with the Discord usernames recently and they seemed to have lost the # part, so sorry if that causes issues.

**Comment by pembem22** [comment]
Hi, feel free to develop your own app for iOS and name it how you like. I don't think it would make sense for you to fork this repository, as the codebase will differ significantly.

**Comment by XboxOneSogie720** [comment]
@pembem22 Right but I wanted to give some form of credit somehow. I'm only 14 i dont know how that legal stuff works or whatever.

I guess I'll just put a link to your repo at the end of my README...

BTW while we're here, I tried using Android x86 to run your App and attempt to downgrade my XTREME 2, but the list of your firmware at your other repo are .bin and the app requires .dfu. Just renaming the file brings up an error.

Checking with the app confirms that mine's a QCC, but the QCC downloads, which are listed here, are only .bin.... Any idea what I could try?

https://github.com/pembem22/jbl-firmware/tree/master/Xtreme%202%20QCC
