### ISSUE TITLE
Question About Your Coding Strategy

### ISSUE THREAD

**Issue by XboxOneSogie720** [pembem22/connect-plus#73]
As I was preparing to write my port to iOS in Swift, I was browsing through your src folder, and was intrigued about the addresses that I've seen in your hardware identification files, specifically "HwModel.kt." 

I've always known that for bigger speakers like the XTREME 2, you could just plug it into your computer via the service port and see the product ID which would show up, in my case, in System Information > USB > JBL XTREME 2 > Product ID on my MacBook Pro.

However, I was wondering how you managed to get the PIDs for the non-USB enabled devices, such as the FLIP 6!
<img width="698" alt="Screenshot 2023-06-17 at 4 11 46 AM" src="https://github.com/pembem22/connect-plus/assets/109363013/b6ce3814-7dd0-4a2d-9123-bfcece55c8e0">

**Comment by pembem22** [comment]
You can find the list of PIDs and other info about models by looking inside the official app's APK. That's my main source of information and resources about speaker protocol and communication.

If you have any other questions, please use the discussions feature instead of issues.

**Comment by XboxOneSogie720** [comment]
@pembem22 I see. I've always used iOS stuff, so I guess that's why I haven't see it there.

Sorry about that, I'll be sure to keep it in Discussions.
