### ISSUE TITLE
Disable startup sound JBL Flip 3

### ISSUE THREAD

**Issue by arsenicks** [pembem22/connect-plus#76]
Hi, first thanks a lot for sharing your work. I want to use my Flip3 as a side bed speaker but the startup sound is wayyyy too loud and anoying, my wife will jump in the bed each time I start it...

So your app seems like the last and only option to disable the startup sound(not even sure it does it). But when I try to flip the "Feedback sounds" switch, the app crash/close, same for the speakerphone mode.

The firmware version of the speaker is 7.9 if that can help in any way and I have the latest realease of connect-plus. I tried with the older version but can'T do anything.

Do you have any idea how can I turn that startup sound off or what's crashing theconnect-plus app ?

Thanks, have a great day!

**Comment by pembem22** [comment]
Hi, it looks like I forgot to hide certain UI elements by default, like the feedback sounds switch and speakerphone mode. When the app connects to the speaker, it gets a list of supported features and shows corresponding UI parts. 

As far as I know, Flip 3 doesn't support the features you mentioned, and that caused the app to crash. I'll release a new build with the bug fixed. Unfortunately, there doesn't seem to be a way to disable the sounds. 

You could try looking into modifying the firmware file and flashing it, but there are many unknowns. I only know that the DFU file for Flip 3 contains raw audio in mono signed 16-bit PCM big-endian format. You can import it into Audacity using the settings I described.

**Comment by arsenicks** [comment]
Oh dammit, thanks for replying. I'll add that to the "I wish I have time TODO list" :P 

Do you want me to keep the issue open if you intend to release a new version related to this "bug" ?

Have a great day!

**Comment by pembem22** [comment]
Took a bit too long, but the new version is out.

**Comment by arsenicks** [comment]
Thanks! Just to confirm, this fix the bug that made the app to crash, this does not enable the flip 3 to disable the startup sound right ?

**Comment by pembem22** [comment]
No, that would require changes to the speaker firmware for the actual support.
