### ISSUE TITLE
Change JBL Charge 5 UUID/Serial Number for Service Mode

### ISSUE THREAD

**Issue by xYundy** [pembem22/connect-plus#77]
Hey! I have two JBL Charge 5 speaker and I want to use it in Service Mode (USB Aux Mode).. But for system they have same serial number / uuid..  There is way to flash one of them with different serial number?

![image](https://github.com/pembem22/connect-plus/assets/21332882/c7120070-d464-44f2-8b95-593b43563c9e)

coreaudiod see only one of them as:

`{"name": "Zgmicro AUDIO", "type": "output", "id": "164", "uid": "AppleUSBAudioEngine:Unknown Manufacturer:Zgmicro AUDIO:962810000000:1"}`

if i unplug second return same thing as above as uid..

**Comment by pembem22** [comment]
Hi, I'm not familiar with the USB side of things of JBL speakers, not sure if I can help you.
