### ISSUE TITLE
here's a new problem

### ISSUE THREAD

**Issue by teapot2008** [pembem22/connect-plus#80]
it's very strange that the 1.20 version is keeping flashback
however,the 1.13 versionis all well
by the way,if I don't connect to my charge 4,it's ok and nothing happened
if I connect it,it will stay for 1 to 2 second and then flashback
I am sure that my phone is Android 13 (miui 14)
please help :(

**Comment by nickobrian** [comment]
hello, how am i able to open the software?

**Comment by pembem22** [comment]
@nickobrian you can download the APK from the [releases page](https://github.com/pembem22/connect-plus/releases).

**Comment by teapot2008** [comment]
> @teapot2008 sorry, I don't understand the problem you're having. What do you mean by 'flashback'?

I am sorry that I used wrong word,and I mean the app might be quited unexpectedly

**Comment by pembem22** [comment]
Please try the latest release.

**Comment by nickobrian** [comment]
alright

**Comment by teapot2008** [comment]
The problem still exists

Uploading Screenrecorder-2024-01-28-20-47-19-419.mp4…

**Comment by teapot2008** [comment]
The problem still exists

Uploading Screenrecorder-2024-01-28-20-47-19-419.mp4…

**Comment by teapot2008** [comment]
The problem still exists

https://github.com/pembem22/connect-plus/assets/151073245/d1374815-f274-4bed-a479-563343078e98

**Comment by pembem22** [comment]
Try this fix: [1.2-release-bass-level-fix.zip](https://github.com/pembem22/connect-plus/files/14083854/1.2-release-bass-level-fix.zip)
Rename the file to .apk to install.

**Comment by teapot2008** [comment]
it's fixed now,thank you for your help 😁

**Comment by nickobrian** [comment]
thanks for the fix!
