### ISSUE TITLE
jbl boombox 2 not connecting

### ISSUE THREAD

**Issue by gamer13124325** [pembem22/connect-plus#81]
i tryed to connect it and it knew that it was a jbl boombox 2 that i had, but it just kept saying connecting to jbl boombox 2 for like 10 minutes

**Comment by gogi-ex777** [comment]
charge 5 too

**Comment by XboxOneSogie720** [comment]
That's because these speakers probably use a different protocol and aren't compatible with this app.

**Comment by teapot2008** [comment]
i think bb2 is unsupported

**Comment by pembem22** [comment]
Duplicate of #64
