### ISSUE TITLE
Crashes when displaying Charge 4 details

### ISSUE THREAD

**Issue by dlxmax** [pembem22/connect-plus#83]
Works fine with my Charge 3, but when my Charge 4 details are displayed it crashes immediately.

[crash log.txt](https://github.com/pembem22/connect-plus/files/15390909/crash.log.txt)

Thanks for this app. I look forward to getting stereo working with this pair!

**Comment by dlxmax** [comment]
@pembem22 any chance you could look at this? Logs were attached. Thank you!

**Comment by pembem22** [comment]
Hi, can you test if the following build has the issue fixed: [1.2.2-rc1-release.zip](https://github.com/user-attachments/files/15944770/1.2.2-rc1-release.zip). Rename .zip into .apk.

**Comment by dlxmax** [comment]
@pembem22 Thank you! Yes, it doesn't crash anymore.
Unfortunately, I can't get it to work with both speakers, but that's a separate issue I'll explore and submit a log for. Thanks again.
